# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./backend/tmp/db:/var/lib/postgresql/data"

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./backend:/$WORKDIR"
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: yarn run dev
    volumes:
      - "./frontend:/$WORKDIR"
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - backend